version: '3.8'

services:
  frontend:
    image: frontend
    build: .
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: backend
    build: .
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - 8000:8080
    depends_on:
      - redis
      - postgres
    container_name: backend

  redis:
    image: redis
    restart: unless-stopped
    container_name: redisproject

  postgres:
    image: postgres
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    container_name: postgres