version: '3.8'

services:
  frontend:
    image: frontend
    build: .
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: backend
    build: .
    ports:
      - 8000:8080
    container_name: backend