version: '3.8'

services:
  frontend:
    build: example-frontend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:81
    container_name: frontend

  backend:
    build: example-backend
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      REQUEST_ORIGIN: http://localhost:81
    depends_on:
      - redis
      - postgres
    container_name: backend

  redis:
    image: redis
    restart: unless-stopped
    container_name: redisproject
    volumes:
      - ./redis:/data

  postgres:
    image: postgres
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    container_name: postgres
    volumes: 
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - 81:81
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf